#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from django import forms

COUNTRY_CHOICES = (
    ('',    'None'),
    ('East Asia & Pacific', (
            ('ASM', 'American Samoa'),
            ('AUS', 'Australia'),
            ('BRN', 'Brunei Darussalam'),
            ('KHM', 'Cambodia'),
            ('CHN', 'China'),
            ('FJI', 'Fiji'),
            ('PYF', 'French Polynesia'),
            ('GUM', 'Guam'),
            ('HKG', 'Hong Kong SAR, China'),
            ('IDN', 'Indonesia'),
            ('JPN', 'Japan'),
            ('KIR', 'Kiribati'),
            ('PRK', 'Korea, Dem. Rep.'),
            ('KOR', 'Korea, Rep.'),
            ('LAO', 'Lao PDR'),
            ('MAC', 'Macao SAR, China'),
            ('MYS', 'Malaysia'),
            ('MHL', 'Marshall Islands'),
            ('FSM', 'Micronesia, Fed. Sts.'),
            ('MNG', 'Mongolia'),
            ('MMR', 'Myanmar'),
            ('NCL', 'New Caledonia'),
            ('NZL', 'New Zealand'),
            ('MNP', 'Northern Mariana Islands'),
            ('PLW', 'Palau'),
            ('PNG', 'Papua New Guinea'),
            ('PHL', 'Philippines'),
            ('WSM', 'Samoa'),
            ('SGP', 'Singapore'),
            ('SLB', 'Solomon Islands'),
            ('THA', 'Thailand'),
            ('TMP', 'Timor-Leste'),
            ('TON', 'Tonga'),
            ('TUV', 'Tuvalu'),
            ('VUT', 'Vanuatu'),
            ('VNM', 'Vietnam'),
        )
    ),
    ('Europe & Central Asia', (
            ('ALB', 'Albania'),
            ('ADO', 'Andorra'),
            ('ARM', 'Armenia'),
            ('AUT', 'Austria'),
            ('AZE', 'Azerbaijan'),
            ('BLR', 'Belarus'),
            ('BEL', 'Belgium'),
            ('BIH', 'Bosnia and Herzegovina'),
            ('BGR', 'Bulgaria'),
            ('CHI', 'Channel Islands'),
            ('HRV', 'Croatia'),
            ('CYP', 'Cyprus'),
            ('CZE', 'Czech Republic'),
            ('DNK', 'Denmark'),
            ('EST', 'Estonia'),
            ('FRO', 'Faeroe Islands'),
            ('FIN', 'Finland'),
            ('FRA', 'France'),
            ('GEO', 'Georgia'),
            ('DEU', 'Germany'),
            ('GIB', 'Gibraltar'),
            ('GRC', 'Greece'),
            ('GRL', 'Greenland'),
            ('HUN', 'Hungary'),
            ('ISL', 'Iceland'),
            ('IRL', 'Ireland'),
            ('IMY', 'Isle of Man'),
            ('ITA', 'Italy'),
            ('KAZ', 'Kazakhstan'),
            ('KSV', 'Kosovo'),
            ('KGZ', 'Kyrgyz Republic'),
            ('LVA', 'Latvia'),
            ('LIE', 'Liechtenstein'),
            ('LTU', 'Lithuania'),
            ('LUX', 'Luxembourg'),
            ('MKD', 'Macedonia, FYR'),
            ('MDA', 'Moldova'),
            ('MCO', 'Monaco'),
            ('MNE', 'Montenegro'),
            ('NLD', 'Netherlands'),
            ('NOR', 'Norway'),
            ('POL', 'Poland'),
            ('PRT', 'Portugal'),
            ('ROM', 'Romania'),
            ('RUS', 'Russian Federation'),
            ('SMR', 'San Marino'),
            ('SRB', 'Serbia'),
            ('SVK', 'Slovak Republic'),
            ('SVN', 'Slovenia'),
            ('ESP', 'Spain'),
            ('SWE', 'Sweden'),
            ('CHE', 'Switzerland'),
            ('TJK', 'Tajikistan'),
            ('TUR', 'Turkey'),
            ('TKM', 'Turkmenistan'),
            ('UKR', 'Ukraine'),
            ('GBR', 'United Kingdom'),
            ('UZB', 'Uzbekistan'),
        )
    ),
    ('Latin America & Caribbean', (
            ('ATG', 'Antigua and Barbuda'),
            ('ARG', 'Argentina'),
            ('ABW', 'Aruba'),
            ('BHS', 'Bahamas, The'),
            ('BRB', 'Barbados'),
            ('BLZ', 'Belize'),
            ('BOL', 'Bolivia'),
            ('BRA', 'Brazil'),
            ('CYM', 'Cayman Islands'),
            ('CHL', 'Chile'),
            ('COL', 'Colombia'),
            ('CRI', 'Costa Rica'),
            ('CUB', 'Cuba'),
            ('DMA', 'Dominica'),
            ('DOM', 'Dominican Republic'),
            ('ECU', 'Ecuador'),
            ('SLV', 'El Salvador'),
            ('GRD', 'Grenada'),
            ('GTM', 'Guatemala'),
            ('GUY', 'Guyana'),
            ('HTI', 'Haiti'),
            ('HND', 'Honduras'),
            ('JAM', 'Jamaica'),
            ('MEX', 'Mexico'),
            ('ANT', 'Netherlands Antilles'),
            ('NIC', 'Nicaragua'),
            ('PAN', 'Panama'),
            ('PRY', 'Paraguay'),
            ('PER', 'Peru'),
            ('PRI', 'Puerto Rico'),
            ('KNA', 'St. Kitts and Nevis'),
            ('LCA', 'St. Lucia'),
            ('VCT', 'St. Vincent and the Grenadines'),
            ('SUR', 'Suriname'),
            ('TTO', 'Trinidad and Tobago'),
            ('TCA', 'Turks and Caicos Islands'),
            ('URY', 'Uruguay'),
            ('VEN', 'Venezuela, RB'),
            ('VIR', 'Virgin Islands (U.S.)'),
        )
    ),
    ('Middle East & North Africa', (
            ('DZA', 'Algeria'),
            ('BHR', 'Bahrain'),
            ('DJI', 'Djibouti'),
            ('EGY', 'Egypt, Arab Rep.'),
            ('IRN', 'Iran, Islamic Rep.'),
            ('IRQ', 'Iraq'),
            ('ISR', 'Israel'),
            ('JOR', 'Jordan'),
            ('KWT', 'Kuwait'),
            ('LBN', 'Lebanon'),
            ('LBY', 'Libya'),
            ('MLT', 'Malta'),
            ('MAR', 'Morocco'),
            ('OMN', 'Oman'),
            ('QAT', 'Qatar'),
            ('SAU', 'Saudi Arabia'),
            ('SYR', 'Syrian Arab Republic'),
            ('TUN', 'Tunisia'),
            ('ARE', 'United Arab Emirates'),
            ('WBG', 'West Bank and Gaza'),
            ('YEM', 'Yemen, Rep.'),
        )
    ),
    ('North America', (
            ('BMU', 'Bermuda'),
            ('CAN', 'Canada'),
            ('USA', 'United States'),
        )
    ),
    ('South Asia', (
            ('AFG', 'Afghanistan'),
            ('BGD', 'Bangladesh'),
            ('BTN', 'Bhutan'),
            ('IND', 'India'),
            ('MDV', 'Maldives'),
            ('NPL', 'Nepal'),
            ('PAK', 'Pakistan'),
            ('LKA', 'Sri Lanka'),
        )
    ),
    ('Sub-Saharan Africa', (
            ('AGO', 'Angola'),
            ('BEN', 'Benin'),
            ('BWA', 'Botswana'),
            ('BFA', 'Burkina Faso'),
            ('BDI', 'Burundi'),
            ('CMR', 'Cameroon'),
            ('CPV', 'Cape Verde'),
            ('CAF', 'Central African Republic'),
            ('TCD', 'Chad'),
            ('COM', 'Comoros'),
            ('ZAR', 'Congo, Dem. Rep.'),
            ('COG', 'Congo, Rep.'),
            ('CIV', 'Côte d\'Ivoire'),
            ('GNQ', 'Equatorial Guinea'),
            ('ERI', 'Eritrea'),
            ('ETH', 'Ethiopia'),
            ('GAB', 'Gabon'),
            ('GMB', 'Gambia, The'),
            ('GHA', 'Ghana'),
            ('GIN', 'Guinea'),
            ('GNB', 'Guinea-Bissau'),
            ('KEN', 'Kenya'),
            ('LSO', 'Lesotho'),
            ('LBR', 'Liberia'),
            ('MDG', 'Madagascar'),
            ('MWI', 'Malawi'),
            ('MLI', 'Mali'),
            ('MRT', 'Mauritania'),
            ('MUS', 'Mauritius'),
            ('MYT', 'Mayotte'),
            ('MOZ', 'Mozambique'),
            ('NAM', 'Namibia'),
            ('NER', 'Niger'),
            ('NGA', 'Nigeria'),
            ('RWA', 'Rwanda'),
            ('STP', 'São Tomé and Principe'),
            ('SEN', 'Senegal'),
            ('SYC', 'Seychelles'),
            ('SLE', 'Sierra Leone'),
            ('SOM', 'Somalia'),
            ('ZAF', 'South Africa'),
            ('SDN', 'Sudan'),
            ('SWZ', 'Swaziland'),
            ('TZA', 'Tanzania'),
            ('TGO', 'Togo'),
            ('UGA', 'Uganda'),
            ('ZMB', 'Zambia'),
            ('ZWE', 'Zimbabwe'),
        )
    ),
)

class SessionSettingsForm(forms.Form):
    start_year = forms.IntegerField(label='Start year', \
                                    required=False, \
                                    min_value=1960, \
                                    max_value=2008, \
                                    widget=forms.TextInput(attrs={'class':'year_entry'}))
    end_year = forms.IntegerField(label='End year', \
                                  required=False, \
                                  min_value=1961, \
                                  max_value=2009, \
                                  widget=forms.TextInput(attrs={'class':'year_entry'}))
    country_one = forms.CharField(label='Filter by country', \
                                  required=False, \
                                  max_length=50, \
                                  widget=forms.Select(choices=COUNTRY_CHOICES))
    country_two = forms.CharField(label='Compare wth', \
                                  required=False, \
                                  max_length=50, \
                                  widget=forms.Select(choices=COUNTRY_CHOICES,attrs={'class':'country_two'}))
                 
